# .github/workflows/deploy.yml
---
name: Deploy

'on':
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: dev
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: app/app.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/intent-classifier:${{ github.sha }}
          platforms: linux/amd64,linux/arm64
